name = "SparsityPattern"
uuid = "58b93f2e-b9c2-11e9-0ae4-071bfa458bf3"
authors = ["Eivind Fonn <evfonn@gmail.com>"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
